version: '3.7'
services:
  redis:
    image: redis:alpine
    ports:
      - 6379:6379
    volumes:
      - redis_data:/data
  api:
    build: .
    ports:
      - 3000:3000
    environment:
      - REDIS_PORT=6379
      - REDIS_HOST=redis
      - PORT=3000

volumes:
    redis_data:
