FROM node:14.16 as build-e2e

WORKDIR /usr/src/app

COPY package*.json ./

RUN npm set loglevel=error && \
    npm set progress=false && \
    npm install && \
    npm install -g @nestjs/cli

COPY . /usr/src/app

ENTRYPOINT ["npm", "run", "test:e2e"]